#+TITLE: My GNU Emacs Configuration
#+AUTHOR: Brian Hoffpauir
#+DATE:
#+EMAIL: nil
#+DESCRIPTION: GNU Emacs Configuration Repository README.
#+LANGUAGE: en

#+BEGIN_COMMENT
% Prefered output format is Plain Text -> ASCII File. Place the result in the
% root directory.
#+END_COMMENT

This repository is for versioning my GNU Emacs configuration files. I hope to
keep them platform independent, so I can use them across all my machines (both
UNIX-like and Windows).

* Note

To use this configuration there should be no /~\slash{}.emacs/ file as this
configuration uses an /init.el/ that is stored in the /~\slash{}.emacs.d/
directory.  Also ensure that when cloning this repository something resembling
following command is used:
#+BEGIN_SRC sh
mv ~/.emacs.d ~/.emacs.d.bak && git clone <url> ~/.emacs.d
#+END_SRC
This configuration uses custom.el as the customize options settings file.

* Packages Used (MELPA)

- use-package
- pomodoro
- php-mode
- lua-mode
- ox-leanpub
- markdown-mode
- 2048-game
- doom-themes

* Key Bindings

- "C-M-y" - Toggle built-in whitespace minor mode.

* License

#+INCLUDE: "../LICENSE"

